version: '3.8'

services:
  # ==================================================
  # API GATEWAY
  # ==================================================
  nginx-service: # 80 - PUBLIC
    container_name: thesis-nginx-service
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/app/logs
    restart: always

  # ==================================================
  # FAKE NEWS DETECTION
  # ==================================================
  fakenewsdetection-service: # 5000 - private
    container_name: thesis-fakenewsdetection-service
    build:
      context: ../
    restart: always
